Threshold aperture
altuson/tess-asteroids pull request #5
Opened 2024-09-11 23:37 UTC by jorgemarpa

Adding a method to compute threhold mask for every frame and create an aperture mask.

2024-09-16 18:34 UTC, altuson commented
Maybe we want to test how the aperture behaves with extreme negatives before merging?

2024-09-17 14:26 UTC, altuson requested changes

2024-09-17 15:44 UTC, jorgemarpa commented
> Maybe we want to test how the aperture behaves with extreme negative pixels before merging?

I tested on a cutout with negative and positive values more than 3 orders of magnitude larger than the background level. The median and MAD are robust to extreme values (see attached figure). The response of the threshold mask is what is expected and stable, all contiguous pixels closer to the reference pixel. I think vetting the pixels in the mask (e.g. saturated, artifacts from subtraction, etc) is a different task not part of creating the threshold mask. 

![image](https://github.com/user-attachments/assets/c726aa70-c2e8-4314-a881-f74e5af752ac)

2024-09-17 19:54 UTC, altuson requested changes

2024-09-17 19:54 UTC, altuson commented on src/tess_asteroids/tpf.py
> +            Method used for apertrue estimation. One of ['threshold', 'prf', 'ellipse'].
```suggestion
            Method used for aperture estimation. One of ['threshold', 'prf', 'ellipse'].
```

2024-09-17 19:54 UTC, altuson commented on src/tess_asteroids/tpf.py
>          Get aperture for LC extraction.
I think we should describe the threshold method specifically.

2024-09-17 19:54 UTC, altuson commented on src/tess_asteroids/tpf.py
> +            reference_pixel = (self.shape[1] / 2, self.shape[0] / 2)
```suggestion
            reference_pixel = ((self.shape[0] - 1) / 2, (self.shape[1] - 1) / 2)
```
Needs to be row,col and must subtract one to get correct midpoint.

2024-09-17 19:54 UTC, altuson commented on src/tess_asteroids/tpf.py
> +            # Calculate the theshold value and mask
```suggestion
            # Calculate the threshold value and mask
```

2024-09-17 19:54 UTC, altuson commented on src/tess_asteroids/tpf.py
> +            # keep all pixels above threhold if asked
```suggestion
            # keep all pixels above threshold if asked
```

2024-09-17 19:54 UTC, altuson commented on src/tess_asteroids/tpf.py
> +            # `label` assignd number labels to each contiguous `True`` values in the threshold
```suggestion
            # `label` assigns number labels to each contiguous `True`` values in the threshold
```

2024-09-19 15:04 UTC, altuson approved these changes
Looks great! Ready to merge.

2024-09-19 15:04 UTC, merged